name: Manual Release Build

#on:
# workflow_dispatch:
#   inputs:
#     version:
#       description: 'Version number (e.g., 1.0.0)'
#      required: true
#      default: '1.0.0-dev'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      
      - name: Update Version
        run: |
          # Update root package.json
          $packageJson = Get-Content -Path package.json -Raw | ConvertFrom-Json
          $packageJson.version = "${{ github.event.inputs.version }}"
          $packageJson | ConvertTo-Json -Depth 100 | Set-Content -Path package.json
          
          # Update desktop package.json
          $desktopPackageJson = Get-Content -Path apps/desktop/package.json -Raw | ConvertFrom-Json
          $desktopPackageJson.version = "${{ github.event.inputs.version }}"
          $desktopPackageJson | ConvertTo-Json -Depth 100 | Set-Content -Path apps/desktop/package.json
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Installer
        run: npm run make:installer
      
      - name: Build ZIP Package
        run: npm run make:zip
      
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: GCASP-Installer
          path: out/make/squirrel.windows/x64/GCASP-${{ github.event.inputs.version }} Setup.exe
      
      - name: Upload ZIP Package
        uses: actions/upload-artifact@v4
        with:
          name: GCASP-ZIP
          path: out/make/zip/win32/x64/GCASP-win32-x64-${{ github.event.inputs.version }}.zip
